### ISSUE TITLE
the extension list doesn't come up and I can't create an image.

### ISSUE THREAD

**Issue by skymagico** [wkpark/sd-webui-model-mixer#111]
When I restart webui after installing, the extension list doesn't come up and I can't create an image.
I uninstalled Model Mixer and the image is created. 
Is there any way to use Model Mixer again?
I really want to use it 
Thank you and good luck

설치후 webui 재시작할때 확장목록이 안불러와져서 이미지 생성이 안되네요
Model Mixer 제거하니 이미지생성되네요 
Model Mixer  다시 사용할 방법이 있을까요?
꼭 사용하고 싶습니다 
감사합니다 수고하세요

**Comment by skymagico** [comment]
![오류1](https://github.com/wkpark/sd-webui-model-mixer/assets/154529410/4215264d-3b08-4533-a846-dded6da94670)
![버전1](https://github.com/wkpark/sd-webui-model-mixer/assets/154529410/85cb1599-4534-4c27-8936-27d192c45ba4)

**Comment by wkpark** [comment]
확장 목록이 안나오더라도 재시작 하지 마시고 F5를 눌러 리로딩하시면 확장 목록이 다시 정상적으로 나올겁니다.
저도 자주 겪는 문제입니다. 원인은 딱히 찾지 못하겠더군요.

If the extension list doesn't appear, you don't have to restart UI, just press F5 to reload and the extension list should appear again.
This happens to me a lot.

**Comment by skymagico** [comment]
역시 시킨대로 하니 잘되네요 감사합니다
제가 독학하다 보니 물어볼때가 없어서 그러는데요
 로라 만드는데 bmaltais/kohya_ss는 설치 자체는 되지만 화면에 ui가 안잡히고 EasyPhoto는 에러나서 설치 자체가 안됩니다
 1.5버전 로라 만드는데 뭐가 따라만드는데 제일좋나요? 
사이트나 자료나 확장제목이라도 가르쳐 주심 감사하겠습니다 혹시 무례한 질문이었다면 무시하셔도 괜찮습니다

감사합니다 수고하세요  ^^

I did exactly what you said and it worked. Thank you.
I'm self-taught, so I don't have time to ask.
 I'm making Laura, but bmaltais/kohya_ss installs itself, but I can't get the ui on the screen, and EasyPhoto doesn't install itself because of an error.
 What is the best way to create a 1.5 version of Laura? 
If you can point me to a site, resource, or extension, I'd appreciate it. If this is a rude question, feel free to ignore it.

Thank you and have a great day
