### ISSUE TITLE
bug with SD Webui Tabs Extension

### ISSUE THREAD

**Issue by lowrankin** [wkpark/sd-webui-model-mixer#152]
when combined with https://github.com/Haoming02/sd-webui-tabs-extension, 
model-mixer is unable to open.  Every other extension I'm using works fine, this issue only affects model-mixer.

**Comment by wkpark** [comment]
model-mixer has different enable checkbox. It hide enable checkbox and use fake checkbox in the accordion
and it causes the incompatibility.
I suspect that DT and ADetailer will not work with the Tabs extension either.
(DT use a similar fake checkbox and ADetailer use newly adapted InputAccordion with a checkbox)

**Comment by wkpark** [comment]
ok. tabs-extension already support DT, and the latest InputAccordion. this bug fixed by  PR #153

thank you for your reporting!
