### ISSUE TITLE
error and I don't know what's wrong.

### ISSUE THREAD

**Issue by kyle215ps3** [wkpark/sd-webui-model-mixer#21]
i don't know what setting is mm finetune and max models
i have model a selected and even had base model and b model
then tried without base model.

*** Error running before_process: C:\Users\123ky\Documents\Automatic 1111\FULL BACKUP\extensions\sd-webui-model-mixer\scripts\model_mixer.py
    Traceback (most recent call last):
      File "C:\Users\123ky\Documents\Automatic 1111\FULL BACKUP\modules\scripts.py", line 511, in before_process
        script.before_process(p, *script_args)
    TypeError: ModelMixerScript.before_process() missing 5 required positional arguments: 'enabled', 'model_a', 'base_model', 'mm_max_models', and 'mm_finetune'

**Comment by wkpark** [comment]
https://github.com/wkpark/sd-webui-model-mixer/assets/232347/7c4606af-9995-428a-a9a1-834f89aaf9a3

**Comment by kyle215ps3** [comment]
> I've encountered a similar error several times recently. This is an issue I recently encountered with the latest sd-webui 1.6.0, and here's how I solved it.
> 
> 1. switching off all extensions and restarting. (Extensions tab -> Apply and Restart UI)
> 2. select a few extensions and restart UI again.
> 3. select all (or all you want to activate) extensions and restart UI again.
just a note im using 1.5.2 
ok I will try this out thank you! :)

**Comment by wkpark** [comment]
Please reopen it if you encounter similar problems.
