### ISSUE TITLE
Add to A1111 Extension List

### ISSUE THREAD

**Issue by CCpt5** [wkpark/sd-webui-model-mixer#3]
Hi, 

Just wanted to mention, if you weren't aware, that you can request having your extension added to the in A1111 list of extensions on this repo page: https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions

I appreciate what you've done so far. Please close if you're aware of this etc.

**Comment by wkpark** [comment]
thank you for reminding me!

**Comment by wkpark** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/190

**Comment by wkpark** [comment]
merged today ^^!
