### ISSUE TITLE
Error checking weights before image generation.

### ISSUE THREAD

**Issue by BurnZeZ** [wkpark/sd-webui-model-mixer#83]
https://github.com/wkpark/sd-webui-model-mixer/blob/09a9d28efe9efb98d9a22c1c0f9a64030722f730/scripts/model_mixer.py#L2799

		changed |= np.array(weights[j][:max_blocks]) != np.array([0.0]*max_blocks)
	TypeError: unsupported operand type(s) for |=: 'list' and 'bool'

**Comment by wkpark** [comment]
thank you for your feedback,

ok. I can reproduce this error case when I was using merge without using MBWs.

will fix it soon.
