### ISSUE TITLE
Rebasin issues (tested against A1111 master and A1111 dev, both clean installed)

### ISSUE THREAD

**Issue by brendanhoar** [wkpark/sd-webui-model-mixer#87]
If Rebasin is selected, regardless if Fast Rebasin is selected, the following error message appears and the merge fails:

...
File "xxxxxxxx\sd-webui-model-mixer\scripts\rebasin\weight_matching.py", line 837, in weight_matching
     perm_sizes = {p: params_a[axes[0][0]].shape[axes[0][1]] for p, axes in ps.perm_to_axes.items() if axes[0][0] in params_b}
    AttributeError: 'NoneType' object has no attribute 'perm_to_axes'

Tried with several models and with several merge methods. The error does not occur if Rebasin is not selected.

cloned A1111 master and dev again to different directories to do clean install checks with the extension and it still gives that error.

-B

**Comment by wkpark** [comment]
thank you for your feedback.

fixed now

This is an old bug that occurs when you do a normal merge without a block-weighted merge.
