### ISSUE TITLE
Produces an error during work

### ISSUE THREAD

**Issue by miasik** [wkpark/sd-webui-model-mixer#93]
A1111 is 1.7
`mode = Add-Diff, alpha = 0.5
Stage #1/2: 100%|███████████████████████████████████████████████████████████████████| 878/878 [00:03<00:00, 253.78it/s]
Check uninitialized #2/2: 100%|██████████████████████████████████████████████████| 878/878 [00:00<00:00, 176040.87it/s]
Rebasin calc...
*** Error running before_process: E:\SD\automatic1111\extensions\sd-webui-model-mixer\scripts\model_mixer.py
    Traceback (most recent call last):
      File "E:\SD\automatic1111\modules\scripts.py", line 710, in before_process
        script.before_process(p, *script_args)
      File "E:\SD\automatic1111\extensions\sd-webui-model-mixer\scripts\model_mixer.py", line 3005, in before_process
        first_permutation, y = weight_matching(permutation_spec, models["model_a"], theta_0, usefp16=usefp16, device=device, full=fullmatching, lap=laplib)
      File "E:\SD\automatic1111\extensions\sd-webui-model-mixer\scripts\rebasin\weight_matching.py", line 837, in weight_matching
        perm_sizes = {p: params_a[axes[0][0]].shape[axes[0][1]] for p, axes in ps.perm_to_axes.items() if axes[0][0] in params_b}
    AttributeError: 'NoneType' object has no attribute 'perm_to_axes'

---`

**Comment by wkpark** [comment]
I guess you are using an outdated version.
this issue has already been reported and fixed in the master branch.

**Comment by miasik** [comment]
> I guess you are using an outdated version. this issue has already been reported and fixed in the master branch.

It's magic. I'm sure that I checked for updates more than twice before reporting. I've updated it not and It's working.
